### ISSUE TITLE
App crash observed on Android with Swift/Samsung keyboard when multiline is set to true 

### ISSUE THREAD

**Issue by msuma268** [arelstone/react-native-email-chip#180]
I am using the latest version of Email Chip Input library. When there are multiple Email Chip components placed one beneath the other with **multiline being set to true**, App crash is observed when **ENter key is pressed on Android (all OS versions) with Swift Keyboard and Samsung keyboard**. This issue is not seen when Enter key is pressed with Gboard.

Scenario:
1) Type in some content in 1st EMail Chip Input
2) Tap on the second chip input and enter some content there.
3) Now tap on the first email chip input and type some content and press return key from soft keyboard on the device. - App crashes. This is a consistent behavior

Please note that the above scenario works perfectly fine when TextInput(RN component) alone is used.

Observed with latest version of email chip input and RN version 0.60.5 & 0.63.3.

Any inputs to address this will be greatly appreciated

Code used to validate has been furnished below:

`import EmailChipInput from '@arelstone/react-native-email-chip';
import React, {Component} from 'react';
import {StyleSheet, View} from 'react-native';
class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <EmailChipInput
          delimiters={[',', ';', ' ']}
          entries={[]}
          TextInputProps={{multiline: true}}
        />
        <EmailChipInput
          delimiters={[',', ';', ' ']}
          entries={[]}
          TextInputProps={{multiline: true}}
        />
       <EmailChipInput
          delimiters={[',', ';', ' ']}
          entries={[]}
          TextInputProps={{multiline: true}}
        />
      </View>
    );
  }
}
export default App;

const styles = StyleSheet.create({
  container: {
    paddingTop: 23,
  },
  input: {
    margin: 15,
    height: 60,
    borderColor: '#7a42f4',
    borderWidth: 1,
  },
});
`

**Comment by arelstone** [comment]
@msuma268 As I read your code, you are missing the `onSubmit`-prop, this could have something to do with the crash you are experiencing. Will adding this this resolve the issue?
If this does not fix the issue, how about setting the entries to an array with a empty string, will this work?

Try something like this:
```jsx
<EmailChilInput
  entries={[""]}
  onSubmit={(entries)=>console.log(entries)}
  TextInputProps={{multiline: true}}
/>
```

By the way. The default values for the `delimiters`-prop is `,`, `;` and `<space>`, so you do not need to add these as a prop when using the component. If you wish to add one or more delimiters, you can import `{DELIMITERS}` and use the three dots to extend this. Like this `[...DELIMITES, 'a', 'b', 'x']`

**Comment by arelstone** [comment]
Closing this due to it being stale. If this issue persists, please reopen it
