### ISSUE TITLE
How to remove email from state

### ISSUE THREAD

**Issue by buscanopaul** [arelstone/react-native-email-chip#321]
Hi, How to remove email from state? 

const [emails, setEmails] = useState<string[]>(['email1@gmail.com','email2@gmail.com']);

<EmailChipInput
    entries={[emails]}
     onSubmit={(emails: string[]) => setEmails({emails})}
/>

**Comment by arelstone** [comment]
Hello @buscanopaul 

When an email is being deleted by tapping the delete icon `onSubmit` should be called with an array of the remaining emails

I can see a few issues with the code you provided.
1. You are parsing the entries as a multidimensional array of string. This should just be a single array of strings like so: `['email1@gmail.com', 'emails2@gmail.com],`
2. When parsing the emails to entries you are wrapping it in an array. This should just be a single array of strings
3. In your `onSubmit` you are setting the result into the state as an object. This should be an array of string

Your code should look something like this:
```tsx
const [emails, setEmails] = useState<string[]>([
  'email1@gmail.com',
  'email2@gmail.com'
]);

<EmailChipInput
  entries={emails}
  onSubmit={setEmails} // or onSubmit={emails => setEmails(emails)}
/>
```

**Comment by arelstone** [comment]
@buscanopaul I'm closing this issue. Please reopen if you did not get an answer to your question
