### ISSUE TITLE
Why getting ReferenceError: Can't find variable: React ? 

### ISSUE THREAD

**Issue by RinaTai** [arelstone/react-native-email-chip#360]
I'm using this library in Expo ?

 Can you please provide me some solution ?

**Comment by arelstone** [comment]
@RinaTai Would you be able to provide an example of your code?

**Comment by RinaTai** [comment]
![Simulator Screen Shot - iPhone 13 - 2022-05-31 at 15 23 14](https://user-images.githubusercontent.com/100259676/171146787-76feb332-c746-4f31-b1fc-c5a92c8e33c6.png)

**Comment by RinaTai** [comment]
> import EmailChipInput from "@arelstone/react-native-email-chip";

> const [emails, setEmails] = useState([]);

> <EmailChipInput
          containerStyle={{ ...style.inputStyle, marginTop: 15 }}
          entries={emails}
          chipContainerStyle={{ backgroundColor: "#EFEFEF", borderRadius: 5 }}
          onSubmit={(emails: string[]) => setEmails(emails)}
        />

![Simulator Screen Shot - iPhone 13 - 2022-05-31 at 15 23 14](https://user-images.githubusercontent.com/100259676/171149360-78d1797e-7f0a-469a-9694-6ae1adc1e7d8.png)

"expo": "~42.0.1"
"@arelstone/react-native-email-chip": "^2.3.0"

**Comment by arelstone** [comment]
Do you have react installed as a dependency in your project? 

This does not seem like an issue with `react-native-email-chip`.

**Comment by tebantebanteban** [comment]
Same here!

**Comment by jpike88** [comment]
@arelstone same problem

**Comment by jpike88** [comment]
The issue appears to be related to how this library has been compiled

**Comment by arelstone** [comment]
@jpike88 Thank you for digging into this. I am sorry, but I do not have time at the moment to look into this.

A pull request would be very much appreciated

**Comment by arelstone** [comment]
@jpike88 @tebantebanteban @RinaTai  this a fix for this has been released at v2.4.0
