### ISSUE TITLE
Email input is not accepting input, whatever I type input is cleared

### ISSUE THREAD

**Issue by saroj-purbey** [arelstone/react-native-email-chip#399]
When typing in the email input, the input is cleared.
My code block is attached below:

```
function PlayerInvitationScreen(props: any) {
    const [emails, setEmails] = useState<string[]>([]);
    return (
       <View>
           <View style={styles.image}>
                <Image source={require('../assets/images/letter.png')}/>
           </View>
           <View style={styles.textContainer}>
               <Text textSize='2xl' style={{fontWeight:'bold'}}>Invite User</Text>
           </View>
           <EmailChipInput
               entries={emails}
               onSubmit={(emails: string[]) => setEmails(emails)}
           />
       </View>
    )
}
```

I am using the version 2.5.2
I have attached the recorded video.

https://user-images.githubusercontent.com/122858470/232407731-8d46991b-9fe3-4dfb-b148-1a0617223494.mov

**Comment by saroj-purbey** [comment]
Hello @arelstone, please help me with the issue.

**Comment by arelstone** [comment]
@saroj-purbey I'm sorry that I havn't seen this issue before now. I've been on a a well deserved vacation.

Have you solved this?

From what I can see your example looks correct

**Comment by arelstone** [comment]
Closing issue due to being stale. Please reopen if issue presists

**Comment by saroj-purbey** [comment]
I am unable to resolve this issue.

**Comment by arelstone** [comment]
@saroj-purbey Sorry for the delay. Life has been busy lately.

Version 2.5.3 has been released which includes a fix for this

**Comment by OMartinez-NeT** [comment]
Hi @arelstone I had the same issue that Saroj has I'm using version `2.5.4`.
